// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	codesender "github.com/andresmeireles/speaker/internal/codesender"
	mock "github.com/stretchr/testify/mock"
)

// CodeSender is an autogenerated mock type for the CodeSender type
type CodeSender struct {
	mock.Mock
}

type CodeSender_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeSender) EXPECT() *CodeSender_Expecter {
	return &CodeSender_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: authCode
func (_m *CodeSender) Add(authCode codesender.AuthCode) error {
	ret := _m.Called(authCode)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(codesender.AuthCode) error); ok {
		r0 = rf(authCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CodeSender_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CodeSender_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - authCode codesender.AuthCode
func (_e *CodeSender_Expecter) Add(authCode interface{}) *CodeSender_Add_Call {
	return &CodeSender_Add_Call{Call: _e.mock.On("Add", authCode)}
}

func (_c *CodeSender_Add_Call) Run(run func(authCode codesender.AuthCode)) *CodeSender_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(codesender.AuthCode))
	})
	return _c
}

func (_c *CodeSender_Add_Call) Return(_a0 error) *CodeSender_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CodeSender_Add_Call) RunAndReturn(run func(codesender.AuthCode) error) *CodeSender_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *CodeSender) GetAll() ([]codesender.AuthCode, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []codesender.AuthCode
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]codesender.AuthCode, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []codesender.AuthCode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]codesender.AuthCode)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CodeSender_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type CodeSender_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *CodeSender_Expecter) GetAll() *CodeSender_GetAll_Call {
	return &CodeSender_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *CodeSender_GetAll_Call) Run(run func()) *CodeSender_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CodeSender_GetAll_Call) Return(_a0 []codesender.AuthCode, _a1 error) *CodeSender_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CodeSender_GetAll_Call) RunAndReturn(run func() ([]codesender.AuthCode, error)) *CodeSender_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: code
func (_m *CodeSender) GetByCode(code string) (codesender.AuthCode, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 codesender.AuthCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (codesender.AuthCode, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) codesender.AuthCode); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(codesender.AuthCode)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CodeSender_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type CodeSender_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - code string
func (_e *CodeSender_Expecter) GetByCode(code interface{}) *CodeSender_GetByCode_Call {
	return &CodeSender_GetByCode_Call{Call: _e.mock.On("GetByCode", code)}
}

func (_c *CodeSender_GetByCode_Call) Run(run func(code string)) *CodeSender_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CodeSender_GetByCode_Call) Return(_a0 codesender.AuthCode, _a1 error) *CodeSender_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CodeSender_GetByCode_Call) RunAndReturn(run func(string) (codesender.AuthCode, error)) *CodeSender_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: authCodeId
func (_m *CodeSender) GetById(authCodeId int) (codesender.AuthCode, error) {
	ret := _m.Called(authCodeId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 codesender.AuthCode
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (codesender.AuthCode, error)); ok {
		return rf(authCodeId)
	}
	if rf, ok := ret.Get(0).(func(int) codesender.AuthCode); ok {
		r0 = rf(authCodeId)
	} else {
		r0 = ret.Get(0).(codesender.AuthCode)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(authCodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CodeSender_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type CodeSender_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - authCodeId int
func (_e *CodeSender_Expecter) GetById(authCodeId interface{}) *CodeSender_GetById_Call {
	return &CodeSender_GetById_Call{Call: _e.mock.On("GetById", authCodeId)}
}

func (_c *CodeSender_GetById_Call) Run(run func(authCodeId int)) *CodeSender_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *CodeSender_GetById_Call) Return(_a0 codesender.AuthCode, _a1 error) *CodeSender_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CodeSender_GetById_Call) RunAndReturn(run func(int) (codesender.AuthCode, error)) *CodeSender_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: authCode
func (_m *CodeSender) Update(authCode codesender.AuthCode) error {
	ret := _m.Called(authCode)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(codesender.AuthCode) error); ok {
		r0 = rf(authCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CodeSender_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CodeSender_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - authCode codesender.AuthCode
func (_e *CodeSender_Expecter) Update(authCode interface{}) *CodeSender_Update_Call {
	return &CodeSender_Update_Call{Call: _e.mock.On("Update", authCode)}
}

func (_c *CodeSender_Update_Call) Run(run func(authCode codesender.AuthCode)) *CodeSender_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(codesender.AuthCode))
	})
	return _c
}

func (_c *CodeSender_Update_Call) Return(_a0 error) *CodeSender_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CodeSender_Update_Call) RunAndReturn(run func(codesender.AuthCode) error) *CodeSender_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCodeSender creates a new instance of CodeSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeSender {
	mock := &CodeSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
