// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	config "github.com/andresmeireles/speaker/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// ConfigRepositoryconfig is an autogenerated mock type for the ConfigRepository type
type ConfigRepositoryconfig struct {
	mock.Mock
}

type ConfigRepositoryconfig_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigRepositoryconfig) EXPECT() *ConfigRepositoryconfig_Expecter {
	return &ConfigRepositoryconfig_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0
func (_m *ConfigRepositoryconfig) Add(_a0 config.Config) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigRepositoryconfig_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type ConfigRepositoryconfig_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 config.Config
func (_e *ConfigRepositoryconfig_Expecter) Add(_a0 interface{}) *ConfigRepositoryconfig_Add_Call {
	return &ConfigRepositoryconfig_Add_Call{Call: _e.mock.On("Add", _a0)}
}

func (_c *ConfigRepositoryconfig_Add_Call) Run(run func(_a0 config.Config)) *ConfigRepositoryconfig_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Config))
	})
	return _c
}

func (_c *ConfigRepositoryconfig_Add_Call) Return(_a0 error) *ConfigRepositoryconfig_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigRepositoryconfig_Add_Call) RunAndReturn(run func(config.Config) error) *ConfigRepositoryconfig_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *ConfigRepositoryconfig) Delete(_a0 config.Config) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigRepositoryconfig_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ConfigRepositoryconfig_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 config.Config
func (_e *ConfigRepositoryconfig_Expecter) Delete(_a0 interface{}) *ConfigRepositoryconfig_Delete_Call {
	return &ConfigRepositoryconfig_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *ConfigRepositoryconfig_Delete_Call) Run(run func(_a0 config.Config)) *ConfigRepositoryconfig_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Config))
	})
	return _c
}

func (_c *ConfigRepositoryconfig_Delete_Call) Return(_a0 error) *ConfigRepositoryconfig_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigRepositoryconfig_Delete_Call) RunAndReturn(run func(config.Config) error) *ConfigRepositoryconfig_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *ConfigRepositoryconfig) GetAll() ([]config.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]config.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []config.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigRepositoryconfig_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ConfigRepositoryconfig_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *ConfigRepositoryconfig_Expecter) GetAll() *ConfigRepositoryconfig_GetAll_Call {
	return &ConfigRepositoryconfig_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *ConfigRepositoryconfig_GetAll_Call) Run(run func()) *ConfigRepositoryconfig_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigRepositoryconfig_GetAll_Call) Return(_a0 []config.Config, _a1 error) *ConfigRepositoryconfig_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigRepositoryconfig_GetAll_Call) RunAndReturn(run func() ([]config.Config, error)) *ConfigRepositoryconfig_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *ConfigRepositoryconfig) GetById(id int) (*config.Config, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*config.Config, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *config.Config); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigRepositoryconfig_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type ConfigRepositoryconfig_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id int
func (_e *ConfigRepositoryconfig_Expecter) GetById(id interface{}) *ConfigRepositoryconfig_GetById_Call {
	return &ConfigRepositoryconfig_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *ConfigRepositoryconfig_GetById_Call) Run(run func(id int)) *ConfigRepositoryconfig_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ConfigRepositoryconfig_GetById_Call) Return(_a0 *config.Config, _a1 error) *ConfigRepositoryconfig_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigRepositoryconfig_GetById_Call) RunAndReturn(run func(int) (*config.Config, error)) *ConfigRepositoryconfig_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: name
func (_m *ConfigRepositoryconfig) GetByName(name string) (*config.Config, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.Config, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *config.Config); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigRepositoryconfig_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type ConfigRepositoryconfig_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *ConfigRepositoryconfig_Expecter) GetByName(name interface{}) *ConfigRepositoryconfig_GetByName_Call {
	return &ConfigRepositoryconfig_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *ConfigRepositoryconfig_GetByName_Call) Run(run func(name string)) *ConfigRepositoryconfig_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigRepositoryconfig_GetByName_Call) Return(_a0 *config.Config, _a1 error) *ConfigRepositoryconfig_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigRepositoryconfig_GetByName_Call) RunAndReturn(run func(string) (*config.Config, error)) *ConfigRepositoryconfig_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *ConfigRepositoryconfig) Update(_a0 config.Config) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigRepositoryconfig_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConfigRepositoryconfig_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 config.Config
func (_e *ConfigRepositoryconfig_Expecter) Update(_a0 interface{}) *ConfigRepositoryconfig_Update_Call {
	return &ConfigRepositoryconfig_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *ConfigRepositoryconfig_Update_Call) Run(run func(_a0 config.Config)) *ConfigRepositoryconfig_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Config))
	})
	return _c
}

func (_c *ConfigRepositoryconfig_Update_Call) Return(_a0 error) *ConfigRepositoryconfig_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigRepositoryconfig_Update_Call) RunAndReturn(run func(config.Config) error) *ConfigRepositoryconfig_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigRepositoryconfig creates a new instance of ConfigRepositoryconfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigRepositoryconfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigRepositoryconfig {
	mock := &ConfigRepositoryconfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
