// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	invite "github.com/andresmeireles/speaker/internal/invite"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// InviteRepositoryinvite is an autogenerated mock type for the InviteRepository type
type InviteRepositoryinvite struct {
	mock.Mock
}

type InviteRepositoryinvite_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteRepositoryinvite) EXPECT() *InviteRepositoryinvite_Expecter {
	return &InviteRepositoryinvite_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0
func (_m *InviteRepositoryinvite) Add(_a0 invite.Invite) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(invite.Invite) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepositoryinvite_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type InviteRepositoryinvite_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 invite.Invite
func (_e *InviteRepositoryinvite_Expecter) Add(_a0 interface{}) *InviteRepositoryinvite_Add_Call {
	return &InviteRepositoryinvite_Add_Call{Call: _e.mock.On("Add", _a0)}
}

func (_c *InviteRepositoryinvite_Add_Call) Run(run func(_a0 invite.Invite)) *InviteRepositoryinvite_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(invite.Invite))
	})
	return _c
}

func (_c *InviteRepositoryinvite_Add_Call) Return(_a0 error) *InviteRepositoryinvite_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepositoryinvite_Add_Call) RunAndReturn(run func(invite.Invite) error) *InviteRepositoryinvite_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *InviteRepositoryinvite) Delete(_a0 invite.Invite) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(invite.Invite) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepositoryinvite_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InviteRepositoryinvite_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 invite.Invite
func (_e *InviteRepositoryinvite_Expecter) Delete(_a0 interface{}) *InviteRepositoryinvite_Delete_Call {
	return &InviteRepositoryinvite_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *InviteRepositoryinvite_Delete_Call) Run(run func(_a0 invite.Invite)) *InviteRepositoryinvite_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(invite.Invite))
	})
	return _c
}

func (_c *InviteRepositoryinvite_Delete_Call) Return(_a0 error) *InviteRepositoryinvite_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepositoryinvite_Delete_Call) RunAndReturn(run func(invite.Invite) error) *InviteRepositoryinvite_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrdered provides a mock function with given fields: field, asc
func (_m *InviteRepositoryinvite) GetAllOrdered(field string, asc bool) ([]invite.Invite, error) {
	ret := _m.Called(field, asc)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrdered")
	}

	var r0 []invite.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) ([]invite.Invite, error)); ok {
		return rf(field, asc)
	}
	if rf, ok := ret.Get(0).(func(string, bool) []invite.Invite); ok {
		r0 = rf(field, asc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invite.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(field, asc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepositoryinvite_GetAllOrdered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrdered'
type InviteRepositoryinvite_GetAllOrdered_Call struct {
	*mock.Call
}

// GetAllOrdered is a helper method to define mock.On call
//   - field string
//   - asc bool
func (_e *InviteRepositoryinvite_Expecter) GetAllOrdered(field interface{}, asc interface{}) *InviteRepositoryinvite_GetAllOrdered_Call {
	return &InviteRepositoryinvite_GetAllOrdered_Call{Call: _e.mock.On("GetAllOrdered", field, asc)}
}

func (_c *InviteRepositoryinvite_GetAllOrdered_Call) Run(run func(field string, asc bool)) *InviteRepositoryinvite_GetAllOrdered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *InviteRepositoryinvite_GetAllOrdered_Call) Return(_a0 []invite.Invite, _a1 error) *InviteRepositoryinvite_GetAllOrdered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepositoryinvite_GetAllOrdered_Call) RunAndReturn(run func(string, bool) ([]invite.Invite, error)) *InviteRepositoryinvite_GetAllOrdered_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *InviteRepositoryinvite) GetById(id int) (*invite.Invite, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *invite.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*invite.Invite, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *invite.Invite); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invite.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepositoryinvite_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type InviteRepositoryinvite_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id int
func (_e *InviteRepositoryinvite_Expecter) GetById(id interface{}) *InviteRepositoryinvite_GetById_Call {
	return &InviteRepositoryinvite_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *InviteRepositoryinvite_GetById_Call) Run(run func(id int)) *InviteRepositoryinvite_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *InviteRepositoryinvite_GetById_Call) Return(_a0 *invite.Invite, _a1 error) *InviteRepositoryinvite_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepositoryinvite_GetById_Call) RunAndReturn(run func(int) (*invite.Invite, error)) *InviteRepositoryinvite_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPersonId provides a mock function with given fields: id
func (_m *InviteRepositoryinvite) GetByPersonId(id int) ([]invite.Invite, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByPersonId")
	}

	var r0 []invite.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]invite.Invite, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []invite.Invite); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invite.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepositoryinvite_GetByPersonId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPersonId'
type InviteRepositoryinvite_GetByPersonId_Call struct {
	*mock.Call
}

// GetByPersonId is a helper method to define mock.On call
//   - id int
func (_e *InviteRepositoryinvite_Expecter) GetByPersonId(id interface{}) *InviteRepositoryinvite_GetByPersonId_Call {
	return &InviteRepositoryinvite_GetByPersonId_Call{Call: _e.mock.On("GetByPersonId", id)}
}

func (_c *InviteRepositoryinvite_GetByPersonId_Call) Run(run func(id int)) *InviteRepositoryinvite_GetByPersonId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *InviteRepositoryinvite_GetByPersonId_Call) Return(_a0 []invite.Invite, _a1 error) *InviteRepositoryinvite_GetByPersonId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepositoryinvite_GetByPersonId_Call) RunAndReturn(run func(int) ([]invite.Invite, error)) *InviteRepositoryinvite_GetByPersonId_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, values
func (_m *InviteRepositoryinvite) Query(query string, values ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, values...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(query, values...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = rf(query, values...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, values...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepositoryinvite_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type InviteRepositoryinvite_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - values ...interface{}
func (_e *InviteRepositoryinvite_Expecter) Query(query interface{}, values ...interface{}) *InviteRepositoryinvite_Query_Call {
	return &InviteRepositoryinvite_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, values...)...)}
}

func (_c *InviteRepositoryinvite_Query_Call) Run(run func(query string, values ...interface{})) *InviteRepositoryinvite_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *InviteRepositoryinvite_Query_Call) Return(_a0 *sql.Rows, _a1 error) *InviteRepositoryinvite_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepositoryinvite_Query_Call) RunAndReturn(run func(string, ...interface{}) (*sql.Rows, error)) *InviteRepositoryinvite_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *InviteRepositoryinvite) Update(_a0 invite.Invite) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(invite.Invite) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepositoryinvite_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InviteRepositoryinvite_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 invite.Invite
func (_e *InviteRepositoryinvite_Expecter) Update(_a0 interface{}) *InviteRepositoryinvite_Update_Call {
	return &InviteRepositoryinvite_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *InviteRepositoryinvite_Update_Call) Run(run func(_a0 invite.Invite)) *InviteRepositoryinvite_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(invite.Invite))
	})
	return _c
}

func (_c *InviteRepositoryinvite_Update_Call) Return(_a0 error) *InviteRepositoryinvite_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepositoryinvite_Update_Call) RunAndReturn(run func(invite.Invite) error) *InviteRepositoryinvite_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: _a0, status
func (_m *InviteRepositoryinvite) UpdateStatus(_a0 invite.Invite, status int) error {
	ret := _m.Called(_a0, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(invite.Invite, int) error); ok {
		r0 = rf(_a0, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepositoryinvite_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type InviteRepositoryinvite_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - _a0 invite.Invite
//   - status int
func (_e *InviteRepositoryinvite_Expecter) UpdateStatus(_a0 interface{}, status interface{}) *InviteRepositoryinvite_UpdateStatus_Call {
	return &InviteRepositoryinvite_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", _a0, status)}
}

func (_c *InviteRepositoryinvite_UpdateStatus_Call) Run(run func(_a0 invite.Invite, status int)) *InviteRepositoryinvite_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(invite.Invite), args[1].(int))
	})
	return _c
}

func (_c *InviteRepositoryinvite_UpdateStatus_Call) Return(_a0 error) *InviteRepositoryinvite_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepositoryinvite_UpdateStatus_Call) RunAndReturn(run func(invite.Invite, int) error) *InviteRepositoryinvite_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewInviteRepositoryinvite creates a new instance of InviteRepositoryinvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteRepositoryinvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteRepositoryinvite {
	mock := &InviteRepositoryinvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
