// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	person "github.com/andresmeireles/speaker/internal/person"
	mock "github.com/stretchr/testify/mock"
)

// ActionsInterfaceperson is an autogenerated mock type for the ActionsInterface type
type ActionsInterfaceperson struct {
	mock.Mock
}

type ActionsInterfaceperson_Expecter struct {
	mock *mock.Mock
}

func (_m *ActionsInterfaceperson) EXPECT() *ActionsInterfaceperson_Expecter {
	return &ActionsInterfaceperson_Expecter{mock: &_m.Mock}
}

// RemovePerson provides a mock function with given fields: personId
func (_m *ActionsInterfaceperson) RemovePerson(personId int) error {
	ret := _m.Called(personId)

	if len(ret) == 0 {
		panic("no return value specified for RemovePerson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(personId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActionsInterfaceperson_RemovePerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePerson'
type ActionsInterfaceperson_RemovePerson_Call struct {
	*mock.Call
}

// RemovePerson is a helper method to define mock.On call
//   - personId int
func (_e *ActionsInterfaceperson_Expecter) RemovePerson(personId interface{}) *ActionsInterfaceperson_RemovePerson_Call {
	return &ActionsInterfaceperson_RemovePerson_Call{Call: _e.mock.On("RemovePerson", personId)}
}

func (_c *ActionsInterfaceperson_RemovePerson_Call) Run(run func(personId int)) *ActionsInterfaceperson_RemovePerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ActionsInterfaceperson_RemovePerson_Call) Return(_a0 error) *ActionsInterfaceperson_RemovePerson_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActionsInterfaceperson_RemovePerson_Call) RunAndReturn(run func(int) error) *ActionsInterfaceperson_RemovePerson_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *ActionsInterfaceperson) Write(_a0 person.Person) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(person.Person) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActionsInterfaceperson_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ActionsInterfaceperson_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 person.Person
func (_e *ActionsInterfaceperson_Expecter) Write(_a0 interface{}) *ActionsInterfaceperson_Write_Call {
	return &ActionsInterfaceperson_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *ActionsInterfaceperson_Write_Call) Run(run func(_a0 person.Person)) *ActionsInterfaceperson_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(person.Person))
	})
	return _c
}

func (_c *ActionsInterfaceperson_Write_Call) Return(_a0 error) *ActionsInterfaceperson_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActionsInterfaceperson_Write_Call) RunAndReturn(run func(person.Person) error) *ActionsInterfaceperson_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewActionsInterfaceperson creates a new instance of ActionsInterfaceperson. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActionsInterfaceperson(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActionsInterfaceperson {
	mock := &ActionsInterfaceperson{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
