// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	db "github.com/andresmeireles/speaker/internal/db"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// RepositoryInterfacerepository is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterfacerepository struct {
	mock.Mock
}

type RepositoryInterfacerepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryInterfacerepository) EXPECT() *RepositoryInterfacerepository_Expecter {
	return &RepositoryInterfacerepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: en
func (_m *RepositoryInterfacerepository) Add(en db.Entity) error {
	ret := _m.Called(en)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Entity) error); ok {
		r0 = rf(en)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryInterfacerepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type RepositoryInterfacerepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - en db.Entity
func (_e *RepositoryInterfacerepository_Expecter) Add(en interface{}) *RepositoryInterfacerepository_Add_Call {
	return &RepositoryInterfacerepository_Add_Call{Call: _e.mock.On("Add", en)}
}

func (_c *RepositoryInterfacerepository_Add_Call) Run(run func(en db.Entity)) *RepositoryInterfacerepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.Entity))
	})
	return _c
}

func (_c *RepositoryInterfacerepository_Add_Call) Return(_a0 error) *RepositoryInterfacerepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryInterfacerepository_Add_Call) RunAndReturn(run func(db.Entity) error) *RepositoryInterfacerepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: en
func (_m *RepositoryInterfacerepository) Delete(en db.Entity) error {
	ret := _m.Called(en)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Entity) error); ok {
		r0 = rf(en)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryInterfacerepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RepositoryInterfacerepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - en db.Entity
func (_e *RepositoryInterfacerepository_Expecter) Delete(en interface{}) *RepositoryInterfacerepository_Delete_Call {
	return &RepositoryInterfacerepository_Delete_Call{Call: _e.mock.On("Delete", en)}
}

func (_c *RepositoryInterfacerepository_Delete_Call) Run(run func(en db.Entity)) *RepositoryInterfacerepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.Entity))
	})
	return _c
}

func (_c *RepositoryInterfacerepository_Delete_Call) Return(_a0 error) *RepositoryInterfacerepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryInterfacerepository_Delete_Call) RunAndReturn(run func(db.Entity) error) *RepositoryInterfacerepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: table
func (_m *RepositoryInterfacerepository) GetAll(table string) (*sql.Rows, error) {
	ret := _m.Called(table)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*sql.Rows, error)); ok {
		return rf(table)
	}
	if rf, ok := ret.Get(0).(func(string) *sql.Rows); ok {
		r0 = rf(table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(table)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterfacerepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RepositoryInterfacerepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - table string
func (_e *RepositoryInterfacerepository_Expecter) GetAll(table interface{}) *RepositoryInterfacerepository_GetAll_Call {
	return &RepositoryInterfacerepository_GetAll_Call{Call: _e.mock.On("GetAll", table)}
}

func (_c *RepositoryInterfacerepository_GetAll_Call) Run(run func(table string)) *RepositoryInterfacerepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryInterfacerepository_GetAll_Call) Return(_a0 *sql.Rows, _a1 error) *RepositoryInterfacerepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterfacerepository_GetAll_Call) RunAndReturn(run func(string) (*sql.Rows, error)) *RepositoryInterfacerepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: table, id
func (_m *RepositoryInterfacerepository) GetById(table string, id int) (*sql.Row, error) {
	ret := _m.Called(table, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *sql.Row
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*sql.Row, error)); ok {
		return rf(table, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *sql.Row); ok {
		r0 = rf(table, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(table, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterfacerepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type RepositoryInterfacerepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - table string
//   - id int
func (_e *RepositoryInterfacerepository_Expecter) GetById(table interface{}, id interface{}) *RepositoryInterfacerepository_GetById_Call {
	return &RepositoryInterfacerepository_GetById_Call{Call: _e.mock.On("GetById", table, id)}
}

func (_c *RepositoryInterfacerepository_GetById_Call) Run(run func(table string, id int)) *RepositoryInterfacerepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *RepositoryInterfacerepository_GetById_Call) Return(_a0 *sql.Row, _a1 error) *RepositoryInterfacerepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterfacerepository_GetById_Call) RunAndReturn(run func(string, int) (*sql.Row, error)) *RepositoryInterfacerepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: q, args
func (_m *RepositoryInterfacerepository) Query(q string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, q)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(q, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = rf(q, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(q, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterfacerepository_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type RepositoryInterfacerepository_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - q string
//   - args ...interface{}
func (_e *RepositoryInterfacerepository_Expecter) Query(q interface{}, args ...interface{}) *RepositoryInterfacerepository_Query_Call {
	return &RepositoryInterfacerepository_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{q}, args...)...)}
}

func (_c *RepositoryInterfacerepository_Query_Call) Run(run func(q string, args ...interface{})) *RepositoryInterfacerepository_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *RepositoryInterfacerepository_Query_Call) Return(_a0 *sql.Rows, _a1 error) *RepositoryInterfacerepository_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterfacerepository_Query_Call) RunAndReturn(run func(string, ...interface{}) (*sql.Rows, error)) *RepositoryInterfacerepository_Query_Call {
	_c.Call.Return(run)
	return _c
}

// SingleQuery provides a mock function with given fields: q, args
func (_m *RepositoryInterfacerepository) SingleQuery(q string, args ...interface{}) (*sql.Row, error) {
	var _ca []interface{}
	_ca = append(_ca, q)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SingleQuery")
	}

	var r0 *sql.Row
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Row, error)); ok {
		return rf(q, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *sql.Row); ok {
		r0 = rf(q, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(q, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterfacerepository_SingleQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SingleQuery'
type RepositoryInterfacerepository_SingleQuery_Call struct {
	*mock.Call
}

// SingleQuery is a helper method to define mock.On call
//   - q string
//   - args ...interface{}
func (_e *RepositoryInterfacerepository_Expecter) SingleQuery(q interface{}, args ...interface{}) *RepositoryInterfacerepository_SingleQuery_Call {
	return &RepositoryInterfacerepository_SingleQuery_Call{Call: _e.mock.On("SingleQuery",
		append([]interface{}{q}, args...)...)}
}

func (_c *RepositoryInterfacerepository_SingleQuery_Call) Run(run func(q string, args ...interface{})) *RepositoryInterfacerepository_SingleQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *RepositoryInterfacerepository_SingleQuery_Call) Return(_a0 *sql.Row, _a1 error) *RepositoryInterfacerepository_SingleQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterfacerepository_SingleQuery_Call) RunAndReturn(run func(string, ...interface{}) (*sql.Row, error)) *RepositoryInterfacerepository_SingleQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: en
func (_m *RepositoryInterfacerepository) Update(en db.Entity) error {
	ret := _m.Called(en)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Entity) error); ok {
		r0 = rf(en)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryInterfacerepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryInterfacerepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - en db.Entity
func (_e *RepositoryInterfacerepository_Expecter) Update(en interface{}) *RepositoryInterfacerepository_Update_Call {
	return &RepositoryInterfacerepository_Update_Call{Call: _e.mock.On("Update", en)}
}

func (_c *RepositoryInterfacerepository_Update_Call) Run(run func(en db.Entity)) *RepositoryInterfacerepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.Entity))
	})
	return _c
}

func (_c *RepositoryInterfacerepository_Update_Call) Return(_a0 error) *RepositoryInterfacerepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryInterfacerepository_Update_Call) RunAndReturn(run func(db.Entity) error) *RepositoryInterfacerepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryInterfacerepository creates a new instance of RepositoryInterfacerepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterfacerepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterfacerepository {
	mock := &RepositoryInterfacerepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
