// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Etools is an autogenerated mock type for the E type
type Etools struct {
	mock.Mock
}

type Etools_Expecter struct {
	mock *mock.Mock
}

func (_m *Etools) EXPECT() *Etools_Expecter {
	return &Etools_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: message, to
func (_m *Etools) Send(message string, to string) error {
	ret := _m.Called(message, to)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(message, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Etools_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Etools_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - message string
//   - to string
func (_e *Etools_Expecter) Send(message interface{}, to interface{}) *Etools_Send_Call {
	return &Etools_Send_Call{Call: _e.mock.On("Send", message, to)}
}

func (_c *Etools_Send_Call) Run(run func(message string, to string)) *Etools_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Etools_Send_Call) Return(_a0 error) *Etools_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Etools_Send_Call) RunAndReturn(run func(string, string) error) *Etools_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SetFrom provides a mock function with given fields: from
func (_m *Etools) SetFrom(from string) error {
	ret := _m.Called(from)

	if len(ret) == 0 {
		panic("no return value specified for SetFrom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(from)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Etools_SetFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFrom'
type Etools_SetFrom_Call struct {
	*mock.Call
}

// SetFrom is a helper method to define mock.On call
//   - from string
func (_e *Etools_Expecter) SetFrom(from interface{}) *Etools_SetFrom_Call {
	return &Etools_SetFrom_Call{Call: _e.mock.On("SetFrom", from)}
}

func (_c *Etools_SetFrom_Call) Run(run func(from string)) *Etools_SetFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Etools_SetFrom_Call) Return(_a0 error) *Etools_SetFrom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Etools_SetFrom_Call) RunAndReturn(run func(string) error) *Etools_SetFrom_Call {
	_c.Call.Return(run)
	return _c
}

// NewEtools creates a new instance of Etools. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEtools(t interface {
	mock.TestingT
	Cleanup(func())
}) *Etools {
	mock := &Etools{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
