quiet: False
with-expecter: True
dir: "testdata/mocks"
mockname: "{{.InterfaceName}}{{.PackageName}}"
outpkg: "mocks"
filename: "{{.PackageName}}{{.MockName}}.go"
packages:
  github.com/andresmeireles/speaker/internal:
    config:
      recursive: True
