version: '3'
services:
  goweb:
    container_name: sgoweb
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - '.:/app'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - '.:/app'