version: "3"
services:
  goweb:
    container_name: sgoweb
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    command: bash -c "air -c ./build/api/air.toml"
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ".:/app"

  testdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - ".:/app"

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025