# fly.toml app configuration file generated for speaker-api on 2024-01-07T19:33:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "speaker-api"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  APP_PORT="8000"
  APP_URL="https://speaker-api.fly.dev"
  APP_MODE="prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
