name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      testdb:
        image: postgres:latest
        env:
          POSTGRES_DB: speaker
          POSTGRES_USER: speaker
          POSTGRES_PASSWORD: speaker
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build cli
      run: go build -v ./cmd/cli/...

    - name: Build api
      run: go build -v ./cmd/api/...

    - name: Test
      run: go test -v ./...
